### PR TITLE
Added limited comment button support

### PR DESCRIPTION
**Pull request by highperch**
Click “Comment” on Thrillist view pulls up the comment bar and
keyboard, but I couldn’t figure out keyboard sizing and the dismiss by
Tap Gesture isn’t working quite right for some reason…

### CODE REVIEW

**Comment by plainspace** [comment]
I have no clue how to resolve conflicts in an Xcode project. Thoughts?

**Comment by highperch** [comment]
No idea, never tried before. Do these articles help?

https://developer.apple.com/library/ios/recipes/xcode_help-source_control_management/MergingTwoBranches/MergingTwoBranches.html
https://developer.apple.com/library/ios/documentation/ToolsLanguages/Conceptual/Xcode_Overview/UsingSourceCodeControl.html

**Comment by plainspace** [comment]
Let's look at this tomorrow. Would love to figure it out.

**Comment by plainspace** [comment]
@highperch take a look at master now and let me know what you think. Still need to dismiss the keyboard with the post button or a click outside the keyboard.

**Comment by plainspace** [comment]
@highperch got it. pull master. lmk what you think.

**Comment by highperch** [comment]
Ended up merging a few of my suggestions into the master.

**Pull request closed without merging**
